"""empty message

Revision ID: 0579faecd01e
Revises: 22a1a5c53b6d
Create Date: 2022-05-05 15:24:45.610685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0579faecd01e'
down_revision = '22a1a5c53b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('character_fav', sa.Integer(), nullable=True),
    sa.Column('planet_fav', sa.Integer(), nullable=True),
    sa.Column('vehicle_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_fav'], ['character.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['planet_fav'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['vehicle_fav'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
