"""empty message

Revision ID: 282609aa8642
Revises: 0579faecd01e
Create Date: 2022-05-07 09:27:14.326932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282609aa8642'
down_revision = '0579faecd01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_lastname_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_lastname_key', 'user', ['lastname'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
