"""empty message

Revision ID: 28d96599f185
Revises: fd2355d53b31
Create Date: 2022-05-23 16:26:55.647780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d96599f185'
down_revision = 'fd2355d53b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'user', ['id_user'], ['id'])
    op.create_foreign_key(None, 'favorite', 'character', ['character_fav'], ['id'])
    op.create_foreign_key(None, 'favorite', 'planet', ['planet_fav'], ['id'])
    op.create_foreign_key(None, 'favorite', 'vehicle', ['vehicle_fav'], ['id'])
    op.drop_column('favorite', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'id_user')
    # ### end Alembic commands ###
