"""empty message

Revision ID: 6dedfd930955
Revises: 6d6eac6f82c5
Create Date: 2022-05-02 19:32:21.369777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dedfd930955'
down_revision = '6d6eac6f82c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('birth_year', sa.String(length=250), nullable=True),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mass', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('starship', sa.String(length=250), nullable=True),
    sa.Column('vehicles', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
