"""empty message

Revision ID: 99f1e111d497
Revises: b35901d934a5
Create Date: 2022-05-11 19:07:52.808860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f1e111d497'
down_revision = 'b35901d934a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_vehicle_fav_fkey', 'favorite', type_='foreignkey')
    op.drop_constraint('favorite_planet_fav_fkey', 'favorite', type_='foreignkey')
    op.drop_constraint('favorite_id_user_fkey', 'favorite', type_='foreignkey')
    op.drop_constraint('favorite_character_fav_fkey', 'favorite', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favorite_character_fav_fkey', 'favorite', 'character', ['character_fav'], ['id'])
    op.create_foreign_key('favorite_id_user_fkey', 'favorite', 'user', ['id_user'], ['id'])
    op.create_foreign_key('favorite_planet_fav_fkey', 'favorite', 'planet', ['planet_fav'], ['id'])
    op.create_foreign_key('favorite_vehicle_fav_fkey', 'favorite', 'vehicle', ['vehicle_fav'], ['id'])
    # ### end Alembic commands ###
