"""empty message

Revision ID: fd2355d53b31
Revises: 99f1e111d497
Create Date: 2022-05-11 19:17:26.602952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2355d53b31'
down_revision = '99f1e111d497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_column('favorite', 'id_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('favorite', 'userid')
    # ### end Alembic commands ###
